### ISSUE TITLE
出现问题

### ISSUE THREAD

**Issue by fuqiang03** [brvphoenix/wrtbwmon#1]
更新后 无法正常显示速度了 18.06  gcc7.3 
第一个图是手动执行的结果  第二个图是默认的
![qq 20190108222000](https://user-images.githubusercontent.com/26851715/50836345-f8650100-1393-11e9-89c2-1c07914fcff6.png)
![qq 20190108222820](https://user-images.githubusercontent.com/26851715/50836692-c902c400-1394-11e9-9954-f2e771f91efc.png)

**Comment by brvphoenix** [comment]
Update the LuCI to the newest dev branch.
https://github.com/brvphoenix/luci-app-wrtbwmon/tree/dev

**Comment by fuqiang03** [comment]
谢谢 了 已经ok了
