### ISSUE TITLE
It seems that only the client data of br-lan interface can be counted.

### ISSUE THREAD

**Issue by tty228** [brvphoenix/wrtbwmon#2]
Model: Phicomm K3
Architecture: ARMv7 Processor rev 0 (v7l)
Firmware Version: 	OpenWrt 19.07.2 r10947-65030d81f3 / LuCI openwrt-19.07 branch git-20.057.55219-13dd17f （v19.07.2 release）
wrtbwmon: 1.2.0-1
luci-app-wrtbwmon: 2.0.0-2

![1](https://user-images.githubusercontent.com/33397881/78106223-8b6cd980-7425-11ea-8365-356e29155022.png)
![2](https://user-images.githubusercontent.com/33397881/78106493-14841080-7426-11ea-8ae6-21e5b093e316.png)
![3](https://user-images.githubusercontent.com/33397881/78106251-97589b80-7425-11ea-971b-c81f5fd47d4f.png)

The version from pyrovski can be displayed correctly. Did you turn off the detection of other interfaces? Or my own problem.
In addition, WAN interface and LAN interface are not correctly noted.

**Comment by brvphoenix** [comment]
@tty228 
If the total traffic value is zero, it will not been displayed in the table. You can try to turn on the option 'show zero'.

**Comment by tty228** [comment]
> @tty228
> If the total traffic value is zero, it will not been displayed in the table. You can try to turn on the option 'show zero'.

I turned on this option, but still can't display other interface device data.

Device is under 192.168.4.0/24 subnet. It seems that the data of PPPoE WAN interface is not read either.
![捕获](https://user-images.githubusercontent.com/33397881/78169183-96eeed80-7483-11ea-9b01-43b68caffd21.PNG)
![微信截图_20200402014619](https://user-images.githubusercontent.com/33397881/78169314-c30a6e80-7483-11ea-9b43-0d6998339be8.png)

The software works normally when it is in the br-lan interface.

![捕获2](https://user-images.githubusercontent.com/33397881/78169452-fbaa4800-7483-11ea-9939-f8b25753e487.PNG)
![微信截图_20200402015819](https://user-images.githubusercontent.com/33397881/78170407-7889f180-7485-11ea-8ff0-f22ca6820663.png)

**Comment by brvphoenix** [comment]
Try this https://github.com/brvphoenix/wrtbwmon/suites/566313825/artifacts/3753120.

**Comment by tty228** [comment]
![捕获](https://user-images.githubusercontent.com/33397881/78223103-ea4f5300-74f8-11ea-81b5-0bde0d36922a.PNG)

Thank you very much. Now it's great.

**Comment by brvphoenix** [comment]
Besides, the interface with MAC address 00:00:00:00:00:00 is the PPPoE WAN. It is defined by the OpenWrt.
