### ISSUE TITLE
user.notice wrtbwmon: Restart for ifup 

### ISSUE THREAD

**Issue by benisai** [brvphoenix/wrtbwmon#5]
It seems that wrtbwmon is restart the interface. Is there a reason? 

`Fri Apr 15 16:44:41 2022 user.notice wrtbwmon: Restart for ifup of lan0 (lan0)`

**Comment by brvphoenix** [comment]
When action ifup of lan0 is triggered, wrtbwmon will restart itself instead of the interface.
